#163519101 Add page for view and edit user profile
andela/Lit-Kigali1-Frontend pull request #15
Opened 2019-04-23 07:28 UTC by filschristian

#### What does this PR do?
Add page for view and edit profile

#### Description of Task to be completed?
Add user interface that allows a user to view and edit their profile

#### How should this be manually tested?

- Clone the repo

- Run `npm install`

- Run `npm start`

- Log in as a registered user

- Navigate to my profile and view your profile

- Click on edit to update your profile

#### Any background context you want to provide?
You must be registered and authenticated to access this feature

#### What are the relevant pivotal tracker stories?
#163519101

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/22234193/56562575-fa04ae80-65a9-11e9-8e0a-d22e0461c810.png)

![image](https://user-images.githubusercontent.com/22234193/56562595-07219d80-65aa-11e9-98a6-ad562be26e12.png)

#### Questions:
N/A

2019-04-25 12:50 UTC, Nziranziza requested changes

2019-04-25 12:50 UTC, Nziranziza commented on src/config/config.js
> +  upload_url: 'https://api.cloudinary.com/v1_1/litkigaliauthorshaven/image/upload',
I suggest using a .env file for these configurations

2019-04-25 14:53 UTC, mcaleb808 approved these changes

2019-04-26 07:22 UTC, mcaleb808 requested changes
@filschristian and @NkFab, please try to decrease untested lines in your new work!

2019-04-26 09:55 UTC, filschristian commented
**Hello Team, we are adding some functionalities and tests!!!!** 
We are as well working on your reviews.
Thank you

2019-05-02 09:27 UTC, Nziranziza approved these changes

2019-05-02 12:18 UTC, merged